Remove deprecated `--short` flag
The course video suggests that the `--short` flag is deprecated and that it will be removed, yet in the meantime it has been completely removed.

```
$ kubectl version --short
error: unknown flag: --short
See 'kubectl version --help' for usage.
```

Nowadays, running `kubectl version` provides the expected result:

```
$ kubectl version
Client Version: v1.33.2
Kustomize Version: v5.6.0
Server Version: v1.33.2
```